### ISSUE TITLE
More strict typescript?

### ISSUE THREAD

**Issue by roderik** [uport-project/daf#149]
I was wondering if you were open to make the typescript more strict?

By changing the tsconfig to the following, you can find a lot of potential nulls.

```
{
  "compilerOptions": {
    "composite": true,
    "sourceMap": true,
    "inlineSources": true,
    "outDir": "./dist",
    "declaration": true,
    "noImplicitAny": true,
    "esModuleInterop": true,
    "suppressImplicitAnyIndexErrors": true,
    "moduleResolution": "node",
    "skipLibCheck": true,
    "module": "commonjs",
    "target": "es2018",
    "allowJs": false,
    "allowSyntheticDefaultImports": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "forceConsistentCasingInFileNames": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noUnusedLocals": true,
    "strictNullChecks": true,
    "strictBindCallApply": true
  }
}
```

To give you an idea on the fixes that would come to just the tests:

```
 PASS  daf/packages/daf-elem-did/src/__tests__/identity-provider.test.ts
 PASS  daf/packages/daf-core/src/__tests__/default.test.ts
 PASS  daf/packages/daf-trust-graph/src/__tests__/default.test.ts
 PASS  daf/packages/daf-did-comm/src/__tests__/default.test.ts
 PASS  daf/packages/daf-ethr-did/src/__tests__/identity-provider.test.ts
 PASS  daf/packages/daf-resolver-universal/src/__tests__/resolver.test.ts
 PASS  daf/packages/daf-resolver/src/__tests__/resolver.test.ts
 FAIL  daf/packages/daf-libsodium/src/__tests__/secret-box.test.ts
  ● Test suite failed to run

    TypeError: Cannot set property EntityManager of [object Object] which has only a getter

      at Object.<anonymous> (src/index.ts:141:9)
      at Object.<anonymous> (daf/packages/daf-core/src/entities/message.ts:1:1)

 FAIL  daf/packages/daf-selective-disclosure/src/__tests__/helper.test.ts
  ● Test suite failed to run

    TypeError: Cannot set property EntityManager of [object Object] which has only a getter

      at Object.<anonymous> (src/index.ts:141:9)
      at Object.<anonymous> (daf/packages/daf-core/src/entities/message.ts:1:1)

 FAIL  daf/packages/daf-url/src/__tests__/message-handler.test.ts
  ● Test suite failed to run

    TypeError: Cannot set property EntityManager of [object Object] which has only a getter

      at Object.<anonymous> (src/index.ts:141:9)
      at Object.<anonymous> (daf/packages/daf-core/src/entities/message.ts:1:1)

 FAIL  packages/kamuka-agent/src/__tests__/daf.test.ts
  ● Test suite failed to run

    TypeError: Cannot set property EntityManager of [object Object] which has only a getter

      at Object.<anonymous> (src/index.ts:141:9)
      at Object.<anonymous> (daf/packages/daf-core/src/entities/message.ts:1:1)

 FAIL  daf/packages/daf-did-jwt/src/__tests__/message-handler.test.ts
  ● Test suite failed to run

    daf/packages/daf-did-jwt/src/__tests__/message-handler.test.ts:3:1 - error TS6133: 'blake2bHex' is declared but its value is never read.

    3 import { blake2bHex } from 'blakejs'
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

 FAIL  daf/packages/daf-w3c/src/__tests__/credentialStatus.test.ts
  ● Test suite failed to run

    daf/packages/daf-w3c/src/__tests__/credentialStatus.test.ts:3:1 - error TS6133: 'Resolver' is declared but its value is never read.

    3 import { Resolver } from 'did-resolver'
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    daf/packages/daf-w3c/src/__tests__/credentialStatus.test.ts:4:1 - error TS6133: 'ActionSignW3cVp' is declared but its value is never read.

    4 import { ActionSignW3cVp } from '../action-handler'
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

 FAIL  daf/packages/daf-w3c/src/__tests__/action-handler.test.ts
  ● Test suite failed to run

    daf/packages/daf-w3c/src/__tests__/action-handler.test.ts:10:10 - error TS6133: 'W3cActionHandler' is declared but its value is never read.

    10 import { W3cActionHandler, ActionTypes, ActionSignW3cVc, ActionSignW3cVp } from '../index'
                ~~~~~~~~~~~~~~~~
    daf/packages/daf-w3c/src/__tests__/action-handler.test.ts:10:41 - error TS6133: 'ActionSignW3cVc' is declared but its value is never read.

    10 import { W3cActionHandler, ActionTypes, ActionSignW3cVc, ActionSignW3cVp } from '../index'
                                               ~~~~~~~~~~~~~~~
    daf/packages/daf-w3c/src/__tests__/action-handler.test.ts:10:58 - error TS6133: 'ActionSignW3cVp' is declared but its value is never read.

    10 import { W3cActionHandler, ActionTypes, ActionSignW3cVc, ActionSignW3cVp } from '../index'
                                                                ~~~~~~~~~~~~~~~
    daf/packages/daf-w3c/src/__tests__/action-handler.test.ts:16:7 - error TS6133: 'mockAgent' is declared but its value is never read.

    16 const mockAgent = {
             ~~~~~~~~~

 FAIL  daf/packages/daf-core/src/service/__tests__/abstract-service-controller.test.ts
  ● Test suite failed to run

    daf/packages/daf-core/src/service/__tests__/abstract-service-controller.test.ts:1:1 - error TS6133: 'AbstractServiceController' is declared but its value is never read.

    1 import { AbstractServiceController } from '../abstract-service-controller'
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    daf/packages/daf-core/src/service/__tests__/abstract-service-controller.test.ts:2:1 - error TS6133: 'ServiceEventTypes' is declared but its value is never read.

    2 import { ServiceEventTypes } from '../service-manager'
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    daf/packages/daf-core/src/service/__tests__/abstract-service-controller.test.ts:3:1 - error TS6133: 'AbstractIdentity' is declared but its value is never read.

    3 import { AbstractIdentity } from '../../identity/abstract-identity'
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    daf/packages/daf-core/src/service/__tests__/abstract-service-controller.test.ts:4:1 - error TS6133: 'Resolver' is declared but its value is never read.

    4 import { Resolver } from '../../agent'
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    daf/packages/daf-core/src/service/__tests__/abstract-service-controller.test.ts:5:1 - error TS6133: 'Message' is declared but its value is never read.

    5 import { Message } from '../../entities/message'
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

 FAIL  daf/packages/daf-core/src/__tests__/entities.test.ts
  ● Test suite failed to run

    daf/packages/daf-core/src/__tests__/entities.test.ts:2:20 - error TS6133: 'Key' is declared but its value is never read.

    2 import { Identity, Key, Message, Credential, Presentation, Claim } from '../index'
                         ~~~
    daf/packages/daf-core/src/__tests__/entities.test.ts:36:12 - error TS2532: Object is possibly 'undefined'.

    36     expect(fromDb.did).toEqual(identity.did)
                  ~~~~~~
    daf/packages/daf-core/src/__tests__/entities.test.ts:67:12 - error TS2532: Object is possibly 'undefined'.

    67     expect(credential.issuer.did).toEqual(id1.did)
                  ~~~~~~~~~~
    daf/packages/daf-core/src/__tests__/entities.test.ts:68:12 - error TS2532: Object is possibly 'undefined'.

    68     expect(credential.subject.did).toEqual(id2.did)
                  ~~~~~~~~~~
    daf/packages/daf-core/src/__tests__/entities.test.ts:68:12 - error TS2532: Object is possibly 'undefined'.

    68     expect(credential.subject.did).toEqual(id2.did)
                  ~~~~~~~~~~~~~~~~~~
    daf/packages/daf-core/src/__tests__/entities.test.ts:69:12 - error TS2532: Object is possibly 'undefined'.

    69     expect(credential.claims.length).toEqual(3)
                  ~~~~~~~~~~
    daf/packages/daf-core/src/__tests__/entities.test.ts:70:12 - error TS2532: Object is possibly 'undefined'.

    70     expect(credential.claims[0].issuer.did).toEqual(id1.did)
                  ~~~~~~~~~~
    daf/packages/daf-core/src/__tests__/entities.test.ts:71:12 - error TS2532: Object is possibly 'undefined'.

    71     expect(credential.claims[0].subject.did).toEqual(id2.did)
                  ~~~~~~~~~~
    daf/packages/daf-core/src/__tests__/entities.test.ts:71:12 - error TS2532: Object is possibly 'undefined'.

    71     expect(credential.claims[0].subject.did).toEqual(id2.did)
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    daf/packages/daf-core/src/__tests__/entities.test.ts:142:12 - error TS2532: Object is possibly 'undefined'.

    142     expect(message.credentials.length).toEqual(1)
                   ~~~~~~~
    daf/packages/daf-core/src/__tests__/entities.test.ts:143:12 - error TS2532: Object is possibly 'undefined'.

    143     expect(message.credentials[0].claims.length).toEqual(3)
                   ~~~~~~~
    daf/packages/daf-core/src/__tests__/entities.test.ts:144:12 - error TS2532: Object is possibly 'undefined'.

    144     expect(message.presentations.length).toEqual(1)
                   ~~~~~~~
    daf/packages/daf-core/src/__tests__/entities.test.ts:145:12 - error TS2532: Object is possibly 'undefined'.

    145     expect(message.presentations[0].credentials.length).toEqual(1)
                   ~~~~~~~
    daf/packages/daf-core/src/__tests__/entities.test.ts:180:12 - error TS2532: Object is possibly 'undefined'.

    180     expect(fromDb.id).toEqual(customId)
                   ~~~~~~
    daf/packages/daf-core/src/__tests__/entities.test.ts:181:12 - error TS2532: Object is possibly 'undefined'.

    181     expect(fromDb.type).toEqual('custom')
                   ~~~~~~

 FAIL  daf/packages/daf-w3c/src/__tests__/graphql.test.ts
  ● Test suite failed to run

    daf/packages/daf-w3c/src/action-handler.ts:144:36 - error TS2345: Argument of type 'string | undefined' is not assignable to parameter of type 'string'.
      Type 'undefined' is not assignable to type 'string'.

    144         result['exp'] = Date.parse(input[key]) / 1000
                                           ~~~~~~~~~~
    daf/packages/daf-w3c/src/action-handler.ts:176:36 - error TS2345: Argument of type 'string | undefined' is not assignable to parameter of type 'string'.
      Type 'undefined' is not assignable to type 'string'.

    176         result['exp'] = Date.parse(input[key]) / 1000
                                           ~~~~~~~~~~

 FAIL  daf/packages/daf-core/src/message/__tests__/abstract-message-handler.test.ts
  ● Test suite failed to run

    daf/packages/daf-core/src/message/__tests__/abstract-message-handler.test.ts:51:11 - error TS6133: 'handled' is declared but its value is never read.

    51     const handled = await Handler.handle(msg, agent)
                 ~~~~~~~

 FAIL  daf/packages/daf-w3c/src/__tests__/message-handler.test.ts
  ● Test suite failed to run

    daf/packages/daf-w3c/src/__tests__/message-handler.test.ts:100:12 - error TS2532: Object is possibly 'undefined'.

    100     expect(handled.from.did).toEqual(vcPayload.iss)
                   ~~~~~~~~~~~~
    daf/packages/daf-w3c/src/__tests__/message-handler.test.ts:101:12 - error TS2532: Object is possibly 'undefined'.

    101     expect(handled.to.did).toEqual(vcPayload.sub)
                   ~~~~~~~~~~
    daf/packages/daf-w3c/src/__tests__/message-handler.test.ts:116:12 - error TS2532: Object is possibly 'undefined'.

    116     expect(handled.from.did).toEqual(vpPayload.iss)
                   ~~~~~~~~~~~~
    daf/packages/daf-w3c/src/__tests__/message-handler.test.ts:117:12 - error TS2532: Object is possibly 'undefined'.

    117     expect(handled.to.did).toEqual(vpPayload.aud)
                   ~~~~~~~~~~
    daf/packages/daf-w3c/src/__tests__/message-handler.test.ts:133:12 - error TS2532: Object is possibly 'undefined'.

    133     expect(handled.from.did).toEqual(vpMultiAudPayload.iss)
                   ~~~~~~~~~~~~
    daf/packages/daf-w3c/src/__tests__/message-handler.test.ts:134:12 - error TS2532: Object is possibly 'undefined'.

    134     expect(handled.to.did).toEqual(vpMultiAudPayload.aud[0])
                   ~~~~~~~~~~
    daf/packages/daf-w3c/src/__tests__/message-handler.test.ts:170:12 - error TS2532: Object is possibly 'undefined'.

    170     expect(handled.from.did).toEqual('did:ethr:0x54d59e3ffd76917f62db702ac354b17f3842955e')
                   ~~~~~~~~~~~~
    daf/packages/daf-w3c/src/__tests__/message-handler.test.ts:171:12 - error TS2532: Object is possibly 'undefined'.

    171     expect(handled.to.did).toEqual('did:web:uport.me')
                   ~~~~~~~~~~

 FAIL  daf/packages/daf-cli/src/__tests__/default.test.ts
  ● Test suite failed to run

    daf/packages/daf-cli/src/__tests__/default.test.ts:1:1 - error TS1208: All files must be modules when the '--isolatedModules' flag is provided.

    1 describe('daf-cli', () => {
      ~~~~~~~~

 FAIL  daf/packages/daf-core/src/__tests__/resolvers.test.ts
  ● Test suite failed to run

    daf/packages/daf-core/src/__tests__/resolvers.test.ts:1:40 - error TS6133: 'In' is declared but its value is never read.

    1 import { createConnection, Connection, In } from 'typeorm'
                                             ~~
    daf/packages/daf-core/src/__tests__/resolvers.test.ts:2:20 - error TS6133: 'Key' is declared but its value is never read.

    2 import { Identity, Key, Message, Credential, Presentation, Claim } from '../index'
                         ~~~
    daf/packages/daf-core/src/__tests__/resolvers.test.ts:2:60 - error TS6133: 'Claim' is declared but its value is never read.

    2 import { Identity, Key, Message, Credential, Presentation, Claim } from '../index'
                                                                 ~~~~~
    daf/packages/daf-core/src/__tests__/resolvers.test.ts:6:1 - error TS6133: 'resolvers' is declared but its value is never read.

    6 import { resolvers } from '../graphql/graphql-identity-manager'
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    daf/packages/daf-core/src/__tests__/resolvers.test.ts:281:11 - error TS6133: 'agent2' is declared but its value is never read.

    281     const agent2 = makeAgent()
                  ~~~~~~
    daf/packages/daf-core/src/__tests__/resolvers.test.ts:295:12 - error TS2532: Object is possibly 'undefined'.

    295     expect(message.raw).toBe('mock')
                   ~~~~~~~
    daf/packages/daf-core/src/__tests__/resolvers.test.ts:298:11 - error TS6133: 'message2' is declared but its value is never read.

    298     const message2 = await Gql.Core.resolvers.Query.message({}, query, { agent, authenticatedDid })
                  ~~~~~~~~
    daf/packages/daf-core/src/__tests__/resolvers.test.ts:299:12 - error TS2532: Object is possibly 'undefined'.

    299     expect(message.raw).toBe('mock')
                   ~~~~~~~

---------------|---------|----------|---------|---------|-------------------
File           | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
---------------|---------|----------|---------|---------|-------------------
All files      |       0 |        0 |       0 |       0 |                   
 src           |       0 |        0 |       0 |       0 |                   
  server.ts    |       0 |        0 |       0 |       0 | 1-5               
 src/gql       |       0 |      100 |     100 |       0 |                   
  mutations.ts |       0 |      100 |     100 |       0 | 1-47              
  queries.ts   |       0 |      100 |     100 |       0 | 1-113             
 src/lib       |       0 |        0 |       0 |       0 |                   
  agent.ts     |       0 |        0 |     100 |       0 | 1-70              
  apollo.ts    |       0 |      100 |       0 |       0 | 1-44              
---------------|---------|----------|---------|---------|-------------------
Summary of all failing tests
 FAIL  daf/packages/daf-libsodium/src/__tests__/secret-box.test.ts
  ● Test suite failed to run

    TypeError: Cannot set property EntityManager of [object Object] which has only a getter

      at Object.<anonymous> (src/index.ts:141:9)
      at Object.<anonymous> (daf/packages/daf-core/src/entities/message.ts:1:1)

 FAIL  daf/packages/daf-selective-disclosure/src/__tests__/helper.test.ts
  ● Test suite failed to run

    TypeError: Cannot set property EntityManager of [object Object] which has only a getter

      at Object.<anonymous> (src/index.ts:141:9)
      at Object.<anonymous> (daf/packages/daf-core/src/entities/message.ts:1:1)

 FAIL  daf/packages/daf-url/src/__tests__/message-handler.test.ts
  ● Test suite failed to run

    TypeError: Cannot set property EntityManager of [object Object] which has only a getter

      at Object.<anonymous> (src/index.ts:141:9)
      at Object.<anonymous> (daf/packages/daf-core/src/entities/message.ts:1:1)

 FAIL  packages/kamuka-agent/src/__tests__/daf.test.ts
  ● Test suite failed to run

    TypeError: Cannot set property EntityManager of [object Object] which has only a getter

      at Object.<anonymous> (src/index.ts:141:9)
      at Object.<anonymous> (daf/packages/daf-core/src/entities/message.ts:1:1)

 FAIL  daf/packages/daf-did-jwt/src/__tests__/message-handler.test.ts
  ● Test suite failed to run

    daf/packages/daf-did-jwt/src/__tests__/message-handler.test.ts:3:1 - error TS6133: 'blake2bHex' is declared but its value is never read.

    3 import { blake2bHex } from 'blakejs'
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

 FAIL  daf/packages/daf-w3c/src/__tests__/credentialStatus.test.ts
  ● Test suite failed to run

    daf/packages/daf-w3c/src/__tests__/credentialStatus.test.ts:3:1 - error TS6133: 'Resolver' is declared but its value is never read.

    3 import { Resolver } from 'did-resolver'
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    daf/packages/daf-w3c/src/__tests__/credentialStatus.test.ts:4:1 - error TS6133: 'ActionSignW3cVp' is declared but its value is never read.

    4 import { ActionSignW3cVp } from '../action-handler'
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

 FAIL  daf/packages/daf-w3c/src/__tests__/action-handler.test.ts
  ● Test suite failed to run

    daf/packages/daf-w3c/src/__tests__/action-handler.test.ts:10:10 - error TS6133: 'W3cActionHandler' is declared but its value is never read.

    10 import { W3cActionHandler, ActionTypes, ActionSignW3cVc, ActionSignW3cVp } from '../index'
                ~~~~~~~~~~~~~~~~
    daf/packages/daf-w3c/src/__tests__/action-handler.test.ts:10:41 - error TS6133: 'ActionSignW3cVc' is declared but its value is never read.

    10 import { W3cActionHandler, ActionTypes, ActionSignW3cVc, ActionSignW3cVp } from '../index'
                                               ~~~~~~~~~~~~~~~
    daf/packages/daf-w3c/src/__tests__/action-handler.test.ts:10:58 - error TS6133: 'ActionSignW3cVp' is declared but its value is never read.

    10 import { W3cActionHandler, ActionTypes, ActionSignW3cVc, ActionSignW3cVp } from '../index'
                                                                ~~~~~~~~~~~~~~~
    daf/packages/daf-w3c/src/__tests__/action-handler.test.ts:16:7 - error TS6133: 'mockAgent' is declared but its value is never read.

    16 const mockAgent = {
             ~~~~~~~~~

 FAIL  daf/packages/daf-core/src/service/__tests__/abstract-service-controller.test.ts
  ● Test suite failed to run

    daf/packages/daf-core/src/service/__tests__/abstract-service-controller.test.ts:1:1 - error TS6133: 'AbstractServiceController' is declared but its value is never read.

    1 import { AbstractServiceController } from '../abstract-service-controller'
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    daf/packages/daf-core/src/service/__tests__/abstract-service-controller.test.ts:2:1 - error TS6133: 'ServiceEventTypes' is declared but its value is never read.

    2 import { ServiceEventTypes } from '../service-manager'
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    daf/packages/daf-core/src/service/__tests__/abstract-service-controller.test.ts:3:1 - error TS6133: 'AbstractIdentity' is declared but its value is never read.

    3 import { AbstractIdentity } from '../../identity/abstract-identity'
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    daf/packages/daf-core/src/service/__tests__/abstract-service-controller.test.ts:4:1 - error TS6133: 'Resolver' is declared but its value is never read.

    4 import { Resolver } from '../../agent'
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    daf/packages/daf-core/src/service/__tests__/abstract-service-controller.test.ts:5:1 - error TS6133: 'Message' is declared but its value is never read.

    5 import { Message } from '../../entities/message'
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

 FAIL  daf/packages/daf-core/src/__tests__/entities.test.ts
  ● Test suite failed to run

    daf/packages/daf-core/src/__tests__/entities.test.ts:2:20 - error TS6133: 'Key' is declared but its value is never read.

    2 import { Identity, Key, Message, Credential, Presentation, Claim } from '../index'
                         ~~~
    daf/packages/daf-core/src/__tests__/entities.test.ts:36:12 - error TS2532: Object is possibly 'undefined'.

    36     expect(fromDb.did).toEqual(identity.did)
                  ~~~~~~
    daf/packages/daf-core/src/__tests__/entities.test.ts:67:12 - error TS2532: Object is possibly 'undefined'.

    67     expect(credential.issuer.did).toEqual(id1.did)
                  ~~~~~~~~~~
    daf/packages/daf-core/src/__tests__/entities.test.ts:68:12 - error TS2532: Object is possibly 'undefined'.

    68     expect(credential.subject.did).toEqual(id2.did)
                  ~~~~~~~~~~
    daf/packages/daf-core/src/__tests__/entities.test.ts:68:12 - error TS2532: Object is possibly 'undefined'.

    68     expect(credential.subject.did).toEqual(id2.did)
                  ~~~~~~~~~~~~~~~~~~
    daf/packages/daf-core/src/__tests__/entities.test.ts:69:12 - error TS2532: Object is possibly 'undefined'.

    69     expect(credential.claims.length).toEqual(3)
                  ~~~~~~~~~~
    daf/packages/daf-core/src/__tests__/entities.test.ts:70:12 - error TS2532: Object is possibly 'undefined'.

    70     expect(credential.claims[0].issuer.did).toEqual(id1.did)
                  ~~~~~~~~~~
    daf/packages/daf-core/src/__tests__/entities.test.ts:71:12 - error TS2532: Object is possibly 'undefined'.

    71     expect(credential.claims[0].subject.did).toEqual(id2.did)
                  ~~~~~~~~~~
    daf/packages/daf-core/src/__tests__/entities.test.ts:71:12 - error TS2532: Object is possibly 'undefined'.

    71     expect(credential.claims[0].subject.did).toEqual(id2.did)
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    daf/packages/daf-core/src/__tests__/entities.test.ts:142:12 - error TS2532: Object is possibly 'undefined'.

    142     expect(message.credentials.length).toEqual(1)
                   ~~~~~~~
    daf/packages/daf-core/src/__tests__/entities.test.ts:143:12 - error TS2532: Object is possibly 'undefined'.

    143     expect(message.credentials[0].claims.length).toEqual(3)
                   ~~~~~~~
    daf/packages/daf-core/src/__tests__/entities.test.ts:144:12 - error TS2532: Object is possibly 'undefined'.

    144     expect(message.presentations.length).toEqual(1)
                   ~~~~~~~
    daf/packages/daf-core/src/__tests__/entities.test.ts:145:12 - error TS2532: Object is possibly 'undefined'.

    145     expect(message.presentations[0].credentials.length).toEqual(1)
                   ~~~~~~~
    daf/packages/daf-core/src/__tests__/entities.test.ts:180:12 - error TS2532: Object is possibly 'undefined'.

    180     expect(fromDb.id).toEqual(customId)
                   ~~~~~~
    daf/packages/daf-core/src/__tests__/entities.test.ts:181:12 - error TS2532: Object is possibly 'undefined'.

    181     expect(fromDb.type).toEqual('custom')
                   ~~~~~~

 FAIL  daf/packages/daf-w3c/src/__tests__/graphql.test.ts
  ● Test suite failed to run

    daf/packages/daf-w3c/src/action-handler.ts:144:36 - error TS2345: Argument of type 'string | undefined' is not assignable to parameter of type 'string'.
      Type 'undefined' is not assignable to type 'string'.

    144         result['exp'] = Date.parse(input[key]) / 1000
                                           ~~~~~~~~~~
    daf/packages/daf-w3c/src/action-handler.ts:176:36 - error TS2345: Argument of type 'string | undefined' is not assignable to parameter of type 'string'.
      Type 'undefined' is not assignable to type 'string'.

    176         result['exp'] = Date.parse(input[key]) / 1000
                                           ~~~~~~~~~~

 FAIL  daf/packages/daf-core/src/message/__tests__/abstract-message-handler.test.ts
  ● Test suite failed to run

    daf/packages/daf-core/src/message/__tests__/abstract-message-handler.test.ts:51:11 - error TS6133: 'handled' is declared but its value is never read.

    51     const handled = await Handler.handle(msg, agent)
                 ~~~~~~~

 FAIL  daf/packages/daf-w3c/src/__tests__/message-handler.test.ts
  ● Test suite failed to run

    daf/packages/daf-w3c/src/__tests__/message-handler.test.ts:100:12 - error TS2532: Object is possibly 'undefined'.

    100     expect(handled.from.did).toEqual(vcPayload.iss)
                   ~~~~~~~~~~~~
    daf/packages/daf-w3c/src/__tests__/message-handler.test.ts:101:12 - error TS2532: Object is possibly 'undefined'.

    101     expect(handled.to.did).toEqual(vcPayload.sub)
                   ~~~~~~~~~~
    daf/packages/daf-w3c/src/__tests__/message-handler.test.ts:116:12 - error TS2532: Object is possibly 'undefined'.

    116     expect(handled.from.did).toEqual(vpPayload.iss)
                   ~~~~~~~~~~~~
    daf/packages/daf-w3c/src/__tests__/message-handler.test.ts:117:12 - error TS2532: Object is possibly 'undefined'.

    117     expect(handled.to.did).toEqual(vpPayload.aud)
                   ~~~~~~~~~~
    daf/packages/daf-w3c/src/__tests__/message-handler.test.ts:133:12 - error TS2532: Object is possibly 'undefined'.

    133     expect(handled.from.did).toEqual(vpMultiAudPayload.iss)
                   ~~~~~~~~~~~~
    daf/packages/daf-w3c/src/__tests__/message-handler.test.ts:134:12 - error TS2532: Object is possibly 'undefined'.

    134     expect(handled.to.did).toEqual(vpMultiAudPayload.aud[0])
                   ~~~~~~~~~~
    daf/packages/daf-w3c/src/__tests__/message-handler.test.ts:170:12 - error TS2532: Object is possibly 'undefined'.

    170     expect(handled.from.did).toEqual('did:ethr:0x54d59e3ffd76917f62db702ac354b17f3842955e')
                   ~~~~~~~~~~~~
    daf/packages/daf-w3c/src/__tests__/message-handler.test.ts:171:12 - error TS2532: Object is possibly 'undefined'.

    171     expect(handled.to.did).toEqual('did:web:uport.me')
                   ~~~~~~~~~~

 FAIL  daf/packages/daf-cli/src/__tests__/default.test.ts
  ● Test suite failed to run

    daf/packages/daf-cli/src/__tests__/default.test.ts:1:1 - error TS1208: All files must be modules when the '--isolatedModules' flag is provided.

    1 describe('daf-cli', () => {
      ~~~~~~~~

 FAIL  daf/packages/daf-core/src/__tests__/resolvers.test.ts
  ● Test suite failed to run

    daf/packages/daf-core/src/__tests__/resolvers.test.ts:1:40 - error TS6133: 'In' is declared but its value is never read.

    1 import { createConnection, Connection, In } from 'typeorm'
                                             ~~
    daf/packages/daf-core/src/__tests__/resolvers.test.ts:2:20 - error TS6133: 'Key' is declared but its value is never read.

    2 import { Identity, Key, Message, Credential, Presentation, Claim } from '../index'
                         ~~~
    daf/packages/daf-core/src/__tests__/resolvers.test.ts:2:60 - error TS6133: 'Claim' is declared but its value is never read.

    2 import { Identity, Key, Message, Credential, Presentation, Claim } from '../index'
                                                                 ~~~~~
    daf/packages/daf-core/src/__tests__/resolvers.test.ts:6:1 - error TS6133: 'resolvers' is declared but its value is never read.

    6 import { resolvers } from '../graphql/graphql-identity-manager'
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    daf/packages/daf-core/src/__tests__/resolvers.test.ts:281:11 - error TS6133: 'agent2' is declared but its value is never read.

    281     const agent2 = makeAgent()
                  ~~~~~~
    daf/packages/daf-core/src/__tests__/resolvers.test.ts:295:12 - error TS2532: Object is possibly 'undefined'.

    295     expect(message.raw).toBe('mock')
                   ~~~~~~~
    daf/packages/daf-core/src/__tests__/resolvers.test.ts:298:11 - error TS6133: 'message2' is declared but its value is never read.

    298     const message2 = await Gql.Core.resolvers.Query.message({}, query, { agent, authenticatedDid })
                  ~~~~~~~~
    daf/packages/daf-core/src/__tests__/resolvers.test.ts:299:12 - error TS2532: Object is possibly 'undefined'.

    299     expect(message.raw).toBe('mock')
                   ~~~~~~~


Test Suites: 14 failed, 7 passed, 21 total
Tests:       10 passed, 10 total
Snapshots:   0 total
Time:        11.16 s, estimated 12 s
```

**Comment by aravindavk** [comment]
> TypeError: Cannot set property EntityManager of [object Object] which has only a getter

>      at Object.<anonymous> (src/index.ts:141:9)
>      at Object.<anonymous> (daf/packages/daf-core/src/entities/message.ts:1:1)

Yesterday I learnt this error is due to an issue with latest version of typeorm. https://github.com/typeorm/typeorm/issues/6054

**Comment by roderik** [comment]
Yeah, that is one issue, but this change in the config activates no implicit any's and strict null checks. 

I'll work on it a bit in https://github.com/uport-project/daf/pull/150 see where I get.

**Comment by roderik** [comment]
PR open
