### ISSUE TITLE
Error: Field "Query.identity" can only be defined once

### ISSUE THREAD

**Issue by Muhammad-Altabba** [uport-project/daf#169]
After upgrading from DAF 3 to DAF 5 I got this error message when running my expressjs server:
```

> yarn build

yarn run v1.22.4
$ tsc
Done in 4.63s.

> yarn start

yarn run v1.22.4
$ node build/index
...
issuer-server/node_modules/graphql/validation/validate.js:125
    throw new Error(errors.map(function (error) {
    ^
Error: Field "Query.identity" can only be defined once.
Field "Query.identities" can only be defined once.
Field "Query.message" can only be defined once.
Field "Query.messages" can only be defined once.
Field "Query.credential" can only be defined once.
Field "Query.credentials" can only be defined once.
    at assertValidSDLExtension (/Repositories/issuer-server/node_modules/graphql/validation/validate.js:125:11)
    at Object.extendSchema (/home/muhammad/Repositories/issuer-server/node_modules/graphql/utilities/extendSchema.js:71:43)
    at Object.buildSchemaFromTypeDefinitions (/home/muhammad/Repositories/issuer-server/node_modules/graphql-tools/dist/generate/buildSchemaFromTypeDefinitions.js:29:28)
    at Object.makeExecutableSchema (/home/muhammad/Repositories/issuer-server/node_modules/graphql-tools/dist/makeExecutableSchema.js:26:29)
    at ApolloServer.initSchema (/home/muhammad/Repositories/issuer-server/node_modules/apollo-server-core/dist/ApolloServer.js:272:49)
    at new ApolloServerBase (/home/muhammad/Repositories/issuer-server/node_modules/apollo-server-core/dist/ApolloServer.js:199:30)
    at new ApolloServer (/home/muhammad/Repositories/issuer-server/node_modules/apollo-server-express/dist/ApolloServer.js:59:9)
    at Object.<anonymous> (/home/muhammad/Repositories/issuer-server/build/apollo.js:20:20)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Repositories/issuer-server/build/server.js:19:16)
error Command failed with exit code 1.
```

Code:
```typescript
import * as Daf from 'daf-core'
import * as DS from 'daf-data-store'

import { W3cGql } from 'daf-w3c'
import { SdrGql } from 'daf-selective-disclosure'

import { ApolloServer } from 'apollo-server-express'
import merge from 'lodash.merge'

import { core, dataStore } from './framework'

const apolloServer = new ApolloServer({
    typeDefs: [
        Daf.Gql.baseTypeDefs,
        DS.Gql.typeDefs, // NOTE: this line is not in the docs (Do n't we need it): https://github.com/uport-project/daf/blob/master/docs/Docs.md#graphql-server
        Daf.Gql.Core.typeDefs,
        Daf.Gql.IdentityManager.typeDefs,
        W3cGql.typeDefs,
        SdrGql.typeDefs,
    ],
    resolvers: merge(
        Daf.Gql.Core.resolvers,
        Daf.Gql.IdentityManager.resolvers,
        DS.Gql.resolvers,
        W3cGql.resolvers,
        SdrGql.resolvers,
    ),
    context: ({ req }) => {
        // Authorization is out of scope for this example,
        // but this is where you could add your auth logic
        // const token = req.headers.authorization || '';
        // if (token !== 'Bearer hardcoded-example-token') {
        //     throw Error('Auth error')
        // }

        return { core, dataStore }
    },
    introspection: true,
});

export { apolloServer }
```

However, removing the line `DS.Gql.typeDefs,` will change the error to:
```
/Repositories/issuer-server/node_modules/graphql-tools/dist/generate/addResolveFunctionsToSchema.js:79
                throw new _1.SchemaError(typeName + "." + fieldName + " defined in resolvers, but not in schema");
                ^
Error: Mutation.deleteMessage defined in resolvers, but not in schema
error Command failed with exit code 1.
```

Thanks,

**Comment by Muhammad-Altabba** [comment]
I resolved the issue by removing both `DS.Gql.typeDefs` and `DS.Gql.resolvers`.
