### ISSUE TITLE
Cannot read property 'identityManager' of undefined

### ISSUE THREAD

**Issue by Muhammad-Altabba** [uport-project/daf#177]
After upgrading to DAF 5 from DAF 3, using `/graphql` with this query gives an error:

```
  query managedIdentities {
    managedIdentities {
      did
    }
  }
```

```
{
  "errors": [
    {
      "message": "Cannot read property 'identityManager' of undefined",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "managedIdentities"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "TypeError: Cannot read property 'identityManager' of undefined",
            "    at /home/muhammad/Repositories/issuer-server/node_modules/daf-core/build/graphql/graphql-identity-manager.js:48:52",
            "    at step (/home/muhammad/Repositories/issuer-server/node_modules/daf-core/build/graphql/graphql-identity-manager.js:33:23)",
            "    at Object.next (/home/muhammad/Repositories/issuer-server/node_modules/daf-core/build/graphql/graphql-identity-manager.js:14:53)",
            "    at /home/muhammad/Repositories/issuer-server/node_modules/daf-core/build/graphql/graphql-identity-manager.js:8:71",
            "    at new Promise (<anonymous>)",
            "    at __awaiter (/home/muhammad/Repositories/issuer-server/node_modules/daf-core/build/graphql/graphql-identity-manager.js:4:12)",
            "    at managedIdentities (/home/muhammad/Repositories/issuer-server/node_modules/daf-core/build/graphql/graphql-identity-manager.js:44:58)",
            "    at field.resolve (/home/muhammad/Repositories/issuer-server/node_modules/graphql-extensions/dist/index.js:133:26)",
            "    at resolveFieldValueOrError (/home/muhammad/Repositories/issuer-server/node_modules/graphql/execution/execute.js:467:18)",
            "    at resolveField (/home/muhammad/Repositories/issuer-server/node_modules/graphql/execution/execute.js:434:16)",
            "    at executeFields (/home/muhammad/Repositories/issuer-server/node_modules/graphql/execution/execute.js:275:18)",
            "    at executeOperation (/home/muhammad/Repositories/issuer-server/node_modules/graphql/execution/execute.js:219:122)",
            "    at executeImpl (/home/muhammad/Repositories/issuer-server/node_modules/graphql/execution/execute.js:104:14)",
            "    at Object.execute (/home/muhammad/Repositories/issuer-server/node_modules/graphql/execution/execute.js:64:35)",
            "    at /home/muhammad/Repositories/issuer-server/node_modules/apollo-server-core/dist/requestPipeline.js:246:46",
            "    at Generator.next (<anonymous>)"
          ]
        }
      }
    }
  ],
  "data": {
    "managedIdentities": null
  }
}
```

I guess there is something wrong with the configuration. What do you suggest?
However, I am following the docs and here how the types and resolvers are defined:
```

const apolloServer = new ApolloServer({
    typeDefs: [
        Daf.Gql.baseTypeDefs,
        Daf.Gql.Core.typeDefs,
        Daf.Gql.IdentityManager.typeDefs,
        W3cGql.typeDefs,
        SdrGql.typeDefs,
    ],
    resolvers: merge(
        Daf.Gql.Core.resolvers,
        Daf.Gql.IdentityManager.resolvers,
        W3cGql.resolvers,
        SdrGql.resolvers,
    ),
    context: ({ req }) => {
        return { core, dataStore }
    },
    introspection: true,
});
```

**Comment by amarts** [comment]
@Muhammad-Altabba daf doesn't have any more dependency on daf-trust-graph (which provided action handler for '/graphql'). You need to do that part (ie, sendJwt) with other handlers, or your own transport mechanisms.

**Comment by Muhammad-Altabba** [comment]
Actually, we already stopped using Trust Graph. We are using /graphql to do a simple query. Can you elaborate more on how Trust Graph is related here? We are querying the `did` of the identities there is not send for `jwt` here.

**Comment by Muhammad-Altabba** [comment]
It turns out that the context variable `core` at `ApolloServer` has to be replaced with `agent`
