### ISSUE TITLE
TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined 

### ISSUE THREAD

**Issue by HamzaBinSarfraz** [uport-project/daf#249]
I am trying to create remote agent using **DAF7 BETA** by using [daf-express](https://github.com/uport-project/daf/blob/beta/docs/api/daf-express.md) and [daf-agent-setup](https://github.com/uport-project/daf/blob/beta/docs/setup.md)
I am using JS instead of TS
But unfortunately i am getting this error

> TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined

Here is the Screenshot of my daf-agent and daf-express

![Screenshot from 2020-10-20 16-10-27](https://user-images.githubusercontent.com/30901435/96578538-c9ace600-12ee-11eb-816f-813d3dcf730d.png)
![Screenshot from 2020-10-20 16-10-25](https://user-images.githubusercontent.com/30901435/96578543-cc0f4000-12ee-11eb-82b9-8376f0d7719a.png)

and here is the complete console.log

> /home/ameer/hamza/git/daf7-remote-agent/node_modules/daf-rest/build/client.js:105
>             finally { if (e_1) throw e_1.error; }
>                                ^
> 
> TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
>     at __values (/home/ameer/hamza/git/daf7-remote-agent/node_modules/daf-rest/build/client.js:50:72)
>     at new AgentRestClient (/home/ameer/hamza/git/daf7-remote-agent/node_modules/daf-rest/build/client.js:95:27)
>     at Object.<anonymous> (/home/ameer/hamza/git/daf7-remote-agent/agent.js:10:5)
>     at Module._compile (internal/modules/cjs/loader.js:778:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
>     at Module.load (internal/modules/cjs/loader.js:653:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
>     at Module.require (internal/modules/cjs/loader.js:692:17)
>     at require (internal/modules/cjs/helpers.js:25:18)

Please lemme know what i am doing wrong here and how to fix this,
Thanks

**Comment by HamzaBinSarfraz** [comment]
**daf remote agent**  needs **supportedMethods** array, that some how not working for me by using 

`import { AgentRestClient, supportedMethods } from 'daf-rest'`

so i figure out this by declaring  supportedMethods array custom

`const supportedMethods = [
  'identityManagerImportIdentity'
];`
